name: Giropops Senhas

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    - name: testando o container do redis
      run: docker run --name redis-server -d -p 6379:6379 redis
      
    - name: Testando o container da aplicação
      run: docker container run --link redis-server:redis-server -d -e REDIS_HOST='redis-server' -p 5000:5000 --name giropops-senhas icaroquintella/linuxtips-giropops-senhas:1.0

  docker:
    needs: test
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    
  build:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    - name: testando o container do redis
      run: docker run --name redis-server -d -p 6379:6379 redis
      
    - name: Testando o container da aplicação
      run: docker container run --link redis-server:redis-server -d -e REDIS_HOST='redis-server' -p 5000:5000 --name giropops-senhas icaroquintella/linuxtips-giropops-senhas:1.0
